---
- hosts: localhost 
  vars:
      helm_chart_url: "https://github.com/ravindra-ui/tf-anbl1.2.git"
      release_name: "prometheuschart"
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: prometheus
        api_version: v1
        kind: Namespace
        state: present    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/helm_repository
        state: directory
    - name: clonechart
      ansible.builtin.git:
        repo: "{{helm_chart_url}}"
        dest: /tmp/helm_repository
        update: no
    - name: Deploy latest version of prometheus chart
      kubernetes.core.helm:
         name: "{{release_name}}"
         chart_ref: /tmp/helm_repository/helm_charts/prometheus
         release_namespace: prometheus
         state: present    
